export const IPC_CHANNELS = {
  LIST_PORTS: 'ports:list',
  LIST_PROCESSES: 'processes:list',
  SCAN_FOLDER: 'folder:scan',
  SCAN_FOLDER_EX: 'folder:scanEx',
  KILL_PROCESS: 'process:kill',
  KILL_PROCESSES: 'process:killMany',
  SYSTEM_INFO: 'system:info',
  SYSTEM_MEMORY: 'system:memory',
  TOGGLE_FLOATING: 'window:toggleFloating',
  PICK_FOLDER: 'dialog:pickFolder',
  REVEAL_IN_FOLDER: 'shell:revealInFolder',
  SPAWN_TEST_PORTS: 'devtools:spawnTestPorts',
  LIST_STARTUPS: 'startup:list',
  SET_STARTUP_ENABLED: 'startup:setEnabled',
  UPDATE_STARTUP: 'startup:update',
  DELETE_STARTUP: 'startup:delete',
  LIST_HOSTS: 'hosts:list',
  SAVE_HOST: 'hosts:save',
  SAVE_HOSTS: 'hosts:saveMany',
  DELETE_HOST: 'hosts:delete',
  TERMINAL_CREATE: 'terminal:create',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_CLOSE: 'terminal:close',
  TERMINAL_DATA: 'terminal:data',
  TERMINAL_EXIT: 'terminal:exit',
  TERMINAL_TOGGLE: 'terminal:toggle',
  SCRIPT_LIST: 'script:list',
  SCRIPT_SAVE: 'script:save',
  SCRIPT_DELETE: 'script:delete',
  SCRIPT_EXECUTE: 'script:execute',
  SCRIPT_STOP: 'script:stop',
  SCRIPT_EVENT: 'script:event'
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
